os: linux
dist: focal

jobs:
  include:
    - name: "job one"
      vm: 
        size: [large]
        use:
          name: 02_image
      script: 
        - echo "condition with job onee"
        - echo $TRAVIS_COMMIT_MESSAGE
        - sleep 50
    - name: "job two"
      vm: 
        size: [large]
        use:
          name: 02_image
      script: 
        - echo "condition with job two"
        - echo $TRAVIS_COMMIT_MESSAGE
        - sleep 60
    - name: "job three"
      vm: 
        size: [large]
        use:
          name: 02_image
      script: 
        - echo "condition with job threee"
        - echo $TRAVIS_COMMIT_MESSAGE
        - sleep 70
