os: linux
dist: focal
vm: 
  create:
    name: root_level_omage

jobs:
  include:
    - name: "job one"
      vm: 
        create:
          name: job_one_level_image
      script: echo "condition with job one"
    - name: "job two"
      #vm: 
      #  create:
      #    name: custom_job_two
      script: echo "condition with job two"
