os: linux
dist: focal
language: generic
vm:
  #size: [large]
  create:
    name: linux_02
before_install:
  - sudo apt-get -y install libxml2-dev
addons:
  apt:
    update: true
script:
  - echo $TRAVIS_COMMIT_MESSAGE
  - sleep 1
  - echo "OK"
