os: linux
dist: focal
deploy:
  provider: gcs
  detect_encoding: true # <== default is false
jobs:
  include:
    - name: "job one"
      vm: 
        create:
          name: custom_job_one_b
      script: echo "condition with job one"
    - name: "job two"
      vm: 
        create:
          name: custom_job_two_b
      script: echo "condition with job two"
    - name: "job three"
      vm: 
        create:
          name: custom_job_three_b
      script: echo "condition with job three"
   
