os: linux
dist: focal

jobs:
  include:
    - name: "job one"
      vm: 
        size: [large]
        create:
          name: 12_june_1
      script: 
        - echo "condition with job onee"
        - echo $TRAVIS_COMMIT_MESSAGE
        - sleep 50
