os: freebsd
#dist: focal
#vm: 
#  create:
#    name: root_image_3

jobs:
  include:
    - name: "job one"
      vm: 
        use:
          name: job_one_level_18
      script: 
        - echo "condition with job one"
        - sleep 70
    - name: "job two"
      vm: 
        use:
          name: job_two_level_15
      script: 
        - echo "condition with job two"
        - sleep 70
