os: linux
dist: focal
jobs:
  include:
    - name: "job one"
      vm: 
        create:
          name: job_one
      script: echo "condition with job one"
    - name: "job two"
      vm: 
        create:
          name: job_two
      script: echo "condition with job two"
     - name: "job three"
      vm: 
        create:
          name: job_three
      script: echo "condition with job three"
   
