os: linux
dist: focal
deploy:
  provider: gcs
  detect_encoding: true # <== default is false
vm: 
  create:
    name: image_one
before_install:
  - sudo apt-get -y install libxml2-dev
addons:
  apt:
    update: true
script:
  - echo "OK8"
