os: linux
dist: bionic

jobs:
  include:
    - name: "job one"
      vm: 
        size: [large]
        create:
          name: 03_june_10
      script: 
        - echo "condition with job onee"
        - echo $TRAVIS_COMMIT_MESSAGE
        - sleep 50
    - name: "job two"
      vm: 
        size: [large]
        create:
          name: 03_june_11
      script: 
        - echo "condition with job two"
        - echo $TRAVIS_COMMIT_MESSAGE
        - sleep 60
    - name: "job three"
      vm: 
        size: [large]
        create:
          name: 03_june_12
      script: 
        - echo "condition with job threeeeee"
        - echo $TRAVIS_COMMIT_MESSAGE
        - sleep 70
