os: linux
dist: focal

jobs:
  include:
    - name: "job one"
      vm: 
        size: [large]
        create:
          name: 03_june_27
      script: 
        - echo "condition with job onee"
        - echo $TRAVIS_COMMIT_MESSAGE
        - sleep 50
    - name: "job two"
      vm: 
        size: [large]
        create:
          name: 03_june_28
      script: 
        - echo "condition with job two"
        - echo $TRAVIS_COMMIT_MESSAGE
        - sleep 60
    - name: "job three"
      vm: 
        size: [large]
        create:
          name: 03_june_29
      script: 
        - echo "condition with job threeeyeee"
        - echo $TRAVIS_COMMIT_MESSAGE
        - sleep 70
