os: linux
dist: focal

jobs:
  include:
    - name: "job one"
      vm: 
        size: [large]
        create:
          name: generic_image_la
      script: 
        - echo "condition with job one"
        - echo $TRAVIS_COMMIT_MESSAGE
        - sleep 50
    - name: "job two"
      vm: 
        size: [large]
        create:
          name: generic_image_lb
      script: 
        - echo "condition with job two"
        - echo $TRAVIS_COMMIT_MESSAGE
        - sleep 60
    - name: "job three"
      vm: 
        size: [large]
        create:
          name: generic_image_lc
      script: 
        - echo "condition with job three"
        - echo $TRAVIS_COMMIT_MESSAGE
        - sleep 70
   
