os: linux
dist: focal
language: generic
vm: 
  size: [large]
  create:
    name: generic_700
before_install:
  - sudo apt-get -y install libxml2-dev
addons:
  apt:
    update: true
script:
  - echo $TRAVIS_COMMIT_MESSAGE
  - sleep 100
  - echo "OK"
  - echo $TRAVIS_COMMIT_MESSAGE
  - sleep 100
  - echo "OK"
  - echo $TRAVIS_COMMIT_MESSAGE
  - sleep 100
  - echo "OK"
  - echo $TRAVIS_COMMIT_MESSAGE
  - sleep 100
  - echo "OK"
  - echo $TRAVIS_COMMIT_MESSAGE
  - sleep 100
  - echo "OK"
  - echo $TRAVIS_COMMIT_MESSAGE
  - sleep 100
  - echo "OK"
  - echo $TRAVIS_COMMIT_MESSAGE
  - sleep 100
  - echo "OK"
