os: linux
dist: focal
arch: s390x
vm: 
  create:
    name: custom_with_arch
before_install:
  - sudo apt-get -y install libxml2-dev
addons:
  apt:
    update: true
script:
  - echo $TRAVIS_COMMIT_MESSAGE
  - echo "OK"
