os: linux
dist: focal
before_install:
  - sudo apt-get -y install libxml2-dev
addons:
  apt:
    update: true
script:
  - echo "OK8"
jobs:
  include:
    - name: "job one"
      vm: 
        create:
          name: job_one
      script: echo "condition with job one"
    - name: "job two"
      vm: 
        create:
          name: job_two
      script: echo "condition with job two"
     - name: "job three"
      vm: 
        create:
          name: job_three
      script: echo "condition with job three"
   
