os: linux
dist: focal

jobs:
  include:
    - name: "job one"
      vm: 
        create:
          name: generic_image
      script: echo "condition with job one"
    - name: "job two"
      vm: 
        create:
          name: generic_image_b
      script: echo "condition with job two"
    - name: "job three"
      vm: 
        create:
          name: generic_image_c
      script: echo "condition with job three"
   
