os: linux
dist: trusty

jobs:
  include:
    - name: "job one"
      vm: 
        size: [large]
        create:
          name: 03_june_13
      script: 
        - echo "condition with job onee"
        - echo $TRAVIS_COMMIT_MESSAGE
        - sleep 50
    - name: "job two"
      vm: 
        size: [large]
        create:
          name: 03_june_14
      script: 
        - echo "condition with job two"
        - echo $TRAVIS_COMMIT_MESSAGE
        - sleep 60
    - name: "job three"
      vm: 
        size: [large]
        create:
          name: 03_june_15
      script: 
        - echo "condition with job threeeeee"
        - echo $TRAVIS_COMMIT_MESSAGE
        - sleep 70
