os: linux
dist: focal
language: generic
vm:
  size: [large]
  create:
    name: large_timeout
before_install:
  - sudo apt-get -y install libxml2-dev
addons:
  apt:
    update: true
script:
  - echo $TRAVIS_COMMIT_MESSAGE
  - sleep 6
  - echo "OK"
