os: linux
dist: focal

jobs:
  include:
    - name: "job one"
      vm:
        create:
          name: 16_june_1
      script: 
        - echo "condition with job onee"
        - echo $TRAVIS_COMMIT_MESSAGE
        - sleep 50
